### PR TITLE
changed range of rand

### PR DESCRIPTION
**Pull request by arhamahmed**
@irfansharif 
minor change, but should yield better results in general

### CODE REVIEW

**Comment by irfansharif** [comment]
i'm not sure i follow, how does this help?

**Comment by arhamahmed** [comment]
i saw it over [here](https://github.com/harthur/brain/blob/master/lib/neuralnetwork.js#L408). im guessing this is based off some best practice or heuristic

**Comment by irfansharif** [comment]
hmm, missed that. try training a bunch of times with each one and if you notice improvements in that there are less number of iterations needed for convergence pull it in.

**Comment by irfansharif** [comment]
closing this after the discussion on your results.

**Pull request closed without merging**
