### PR TITLE
fix for "hidden_layer_sizes" not being assigned when "@hidden_layers" is set

### LINKED ISSUE #15: Error when trying to set number of hidden layers
Hi, I think you have a little bug in "/lib/cerebrum/cerebrum.rb".

Specifically, in the `train` method you have:

```
    hidden_layer_sizes = [ [3, (input_size/2).floor].max ] unless @hidden_layers
    layer_sizes = [input_size, hidden_layer_sizes, output_size].flatten
```

which causes "hidden_layer_sizes" to be nil when @hidden_layers _exists_ and subsequent methods to fail. Maybe you just forgot to assign it, and you probably wanted something like this:

```
hidden_layer_sizes = [ [3, (input_size/2).floor].max ] unless hidden_layer_sizes = @hidden_layers
```

Is it ok if I make a PR ? Cheers.

### PR DESCRIPTION
**Pull request by illtellyoulater**
fixes https://github.com/irfansharif/cerebrum/issues/15

### CODE REVIEW

**Comment by irfansharif** [comment]
thank you for taking the time to investigate this :+1:

**Comment by illtellyoulater** [comment]
Glad I could help, this is a really nice project :).
If this could be of interest to you, it seems that the original JS project got back to life.
I am not sure how though. The author has not been responding for long, but then - looking at https://github.com/harthur/brain/issues/72 - it seems the community started to maintain it again.

**Comment by irfansharif** [comment]
ah. hadn't seen that.
it was an interesting original project but I'm not a very big fan of javascript/node, the lack of a strong standard library puts me off to it. going to closely follow the development of the tensorflow client in ruby, lots of potential there!

**Comment by illtellyoulater** [comment]
I fully agree! :+1: I just thought I would tell you in case you were interested in implementing new features that JS Brain might implement.

On a side note, I am seeing some weird results after training a Cerebrum NN.
Specifically some of the outputs have a value bigger than 1.
My use case is that I have 54 inputs, 2 hidden layers of 8 neurons each, and 54 outputs.
I trained the NN by providing an array of multiple instances of 54 inputs and 54 outputs.

I know this is not the perfect place for discussing it, but just wanted to know if you had seen this kind of behavior yourself before (outputs > 1), so that I may better decide what to do about it.

Thank you!

**Comment by irfansharif** [comment]
interesting, if possible email [me](mailto:irfanmahmoudsharif@gmail.com) the datasets and I can possibly investigate further, though word of note I never intended Cerebrum for serious use more along the lines of working pseudo-code as an instructional tool.

**Comment by robertleeplummerjr** [comment]
Just to note about https://github.com/irfansharif/cerebrum/pull/16#issuecomment-218398509, we have started maintaining it, and if there is anything you see that needs investigated, please open an issue.  We have started to work on recurrent neural nets (https://github.com/harthur-org/brain.js/issues/16), which I'm really excited about.  Very cool to see this lib!

**Pull request merged**
